[tool.briefcase]
project_name = "Analyser"
bundle = "com.phys-pract-amsterdam"
version = "0.0.1"
url = "https://example.com"
license = "GNU General Public License v3 (GPLv3)"
author = 'David Fokkema'
author_email = "d.b.r.a.fokkema@vu.nl"

[tool.briefcase.app.analyser]
formal_name = "Analyser"
description = "My first application"
icon = "src/analyser/resources/analyser"
sources = ['src/analyser']
requires = [
    'setuptools==52.0.0',
    'numpy==1.19.5',
    'pandas==1.2.0',
    'lmfit==1.0.1',
    'PyQt5==5.12.3',
    'pyqtgraph==0.11.0',]

[tool.briefcase.app.analyser.macOS]
requires = []

[tool.briefcase.app.analyser.linux]
requires = []
system_requires = []

[tool.briefcase.app.analyser.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.analyser.iOS]
requires = []

[tool.briefcase.app.analyser.android]
requires = []
