[tool.briefcase]
project_name = "Tailor"
bundle = "com.amsphyslab.tailor"
version = "1.4.2"
url = "https://github.com/davidfokkema/tailor"
license = "GNU General Public License v3 (GPLv3)"
author = 'David Fokkema'
author_email = "d.b.r.a.fokkema@vu.nl"

[tool.briefcase.app.tailor]
formal_name = "Tailor"
description = "Explore datasets and fit models."
icon = "src/tailor/resources/tailor"
sources = ['src/tailor']
requires = [
    'numpy>=1.22.1,<2.0.0',
    'pandas>=1.4.0,<2.0.0',
    'lmfit>=1.0.3,<2.0.0',
    'PySide6>=6.2.2.1,<7.0.0',
    'pyqtgraph>=0.12.3,<0.13.0',
    'matplotlib>=3.5.1,<4.0.0']

[tool.briefcase.app.tailor.macOS]
requires = []

[tool.briefcase.app.tailor.linux]
requires = []
system_requires = []

[tool.briefcase.app.tailor.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.tailor.iOS]
requires = []

[tool.briefcase.app.tailor.android]
requires = []
