[tool.briefcase]
project_name = "Tailor"
bundle = "com.amsphyslab.tailor"
version = "0.8.0"
url = "https://github.com/davidfokkema/tailor"
license = "GNU General Public License v3 (GPLv3)"
author = 'David Fokkema'
author_email = "d.b.r.a.fokkema@vu.nl"

[tool.briefcase.app.tailor]
formal_name = "Tailor"
description = "Explore datasets and fit models."
icon = "src/tailor/resources/tailor"
sources = ['src/tailor']
requires = [
    'setuptools==53.0.0',
    'numpy==1.20.1',
    'pandas==1.2.2',
    'lmfit==1.0.2',
    'PyQt5==5.15.3',
    'pyqtgraph==0.11.1',
    'matplotlib==3.3.4']

[tool.briefcase.app.tailor.macOS]
requires = []

[tool.briefcase.app.tailor.linux]
requires = []
system_requires = []

[tool.briefcase.app.tailor.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.tailor.iOS]
requires = []

[tool.briefcase.app.tailor.android]
requires = []
