[tool.briefcase]
project_name = "Analyser"
bundle = "com.amsphyslab.analyser"
version = "0.1.0"
url = "https://github.com/davidfokkema/analyser"
license = "GNU General Public License v3 (GPLv3)"
author = 'David Fokkema'
author_email = "d.b.r.a.fokkema@vu.nl"

[tool.briefcase.app.analyser]
formal_name = "Analyser"
description = "Explore datasets and fit models."
icon = "src/analyser/resources/analyser"
sources = ['src/analyser']
requires = [
    'setuptools==53.0.0',
    'numpy==1.20.1',
    'pandas==1.2.2',
    'lmfit==1.0.2',
    'PyQt5==5.15.3',
    'pyqtgraph==0.11.1',
    'matplotlib==3.3.4']

[tool.briefcase.app.analyser.macOS]
requires = []

[tool.briefcase.app.analyser.linux]
requires = []
system_requires = []

[tool.briefcase.app.analyser.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.analyser.iOS]
requires = []

[tool.briefcase.app.analyser.android]
requires = []
