name: build-and-upload-installers
on:
  release:
    types: [published]
jobs:
  build-and-upload-installer:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-latest
            filename: macOS/*.dmg
          - os: windows-latest
            filename: windows/*.msi
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install briefcase==0.3.8
      - run: briefcase create
      - run: briefcase build
      - run: python pruner.py
      - run: briefcase package --no-sign
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ matrix.filename }}
          tag: ${{ github.ref }}
